dist: trusty
sudo: required

install:
  - npm install -g sonarqube-scanner

script:
  - sonar-scanner -Dsonar.host.url=https://next.sonarqube.com/sonarqube/

cache:
  directories:
    - '$HOME/.sonar/cache'
